### PR TITLE
Adding Rockford IL Board of Elections

### PR DESCRIPTION
**Pull request by cmccain513**
Adding the Rockford IL Board of Elections site. This is my first pull request into this file, so please forgive me if I didn't do it correctly!

### CODE REVIEW

**Comment by dawnpm** [comment]
Thank you, we're validating your submission.

**Review by dawnpm — CHANGES_REQUESTED** [review]
@cmccain513 I've validated the domain with the city. 

Before I merge this PR, would you please remove the spaces after the commas, and then add the new line to file 1 as well, that's the full list, so we'll want it in both lists.

Thank you.

**Comment by cmccain513** [comment]
ok, think I updated both correctly!

**Review by dawnpm — APPROVED** [review]
Validated addition with Rockford BOE Jorge Paredes via phone 10/15/2020.

Thanks for the submission @cmccain513 .

**Pull request merged**
